language: python
env:
  matrix:
  - SYMPY_VERSION="latest"
  - SYMPY_VERSION="master"
  - SYMPY_VERSION="oldest"
python:
  - 2.7
before_install:
  - sudo apt-get update
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy cython coverage
  - sudo apt-get install phantomjs
  # Theano may try to install SciPy from source if the --no-deps flags isn't
  # there.
  - pip install --no-deps Theano==0.6.0
  - if [[ $SYMPY_VERSION == "oldest" ]]; then
      pip install sympy==0.7.4.1;
    elif [[ $SYMPY_VERSION == "latest" ]]; then
      pip install sympy;
    elif [[ $SYMPY_VERSION == "master" ]]; then
      pip install https://github.com/sympy/sympy/archive/master.zip;
    fi
  - pip install -U nose
  # Note that the `make html` command that runs 'build-sphinx' does not work if
  # Sphinx is installed with 'apt-get install sphinx'. It can't find the
  # numpydoc extension if it is. It must be bypassing virtualenv to the system
  # Python.
  - pip install sphinx numpydoc
  # Install PEP 8 linters (flake8 is like pep8 but also reports unused imports)
  - pip install flake8
before_script:
  - pip --version
  - pip freeze
script:
  # Run Python and Javascript tests.
  - nosetests -v --with-coverage --cover-package=pydy
  # JS tests
  - cd pydy/viz/static/js/tests && phantomjs run-jasmine.js SpecRunner.html
  - cd -  # It should not be combined with above command
  # Check Python and Javascript syntax (trailing whitespaces/newlines, unused imports).
  - (flake8 --select W1,W2,W3 --exclude booger . &&
    flake8 --select F401 --exclude booger,__init__.py,conf.py . &&
    flake8 --select W2,W3 --filename='*.js' examples/ pydy/viz/static/js/dyviz/) ||
    (echo "Please run a linter and fix errors, e.g. pylint, flake8, pep8, etc."; false)
  # Make sure the docs build.
  - cd docs && make html && cd ..
  # Make sure the library installs.
  - python setup.py install
