language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
env:
  matrix:
  - DEP_VERSIONS="oldest"  # Approximately the versions available in the last LTS release of Ubuntu, currently 18.04 LTS.
  - DEP_VERSIONS="latest"
  - DEP_VERSIONS="master"  # Run against SymPy master.
before_install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge  # conda-forge has top precedent
  - conda update -q conda
install:
  - sudo apt-get install phantomjs
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION pip coverage nose flake8 matplotlib sphinx numpydoc jupyter_sphinx
  - source activate test-env
  - if [[ $DEP_VERSIONS == "oldest" ]]; then
      conda install numpy=1.13 scipy=0.19 sympy=1.1 cython=0.26 theano=0.9;
    elif [[ $DEP_VERSIONS == "latest" ]]; then
      conda install numpy scipy sympy cython theano pythreejs;
    elif [[ $DEP_VERSIONS == "master" ]]; then
      conda install numpy scipy cython theano pythreejs;
      pip install https://github.com/sympy/sympy/archive/master.zip;
    fi
before_script:
  - conda info
  - conda list
  - pip --version
  - pip freeze
script:
  # The THEANO_FLAGS are necessary for compilation on Travis CI.
  - THEANO_FLAGS='gcc.cxxflags="-march=core2"' nosetests -v --with-coverage --cover-package=pydy
  # JS tests
  - cd pydy/viz/static/js/tests && phantomjs run-jasmine.js SpecRunner.html
  - cd -  # It should not be combined with above command
  # Check Python and Javascript syntax (trailing whitespaces/newlines, unused imports).
  - (flake8 --select W1,W2,W3 --exclude booger . &&
    flake8 --select F401 --exclude booger,__init__.py,conf.py . &&
    flake8 --select W2,W3 --filename='*.js' examples/ pydy/viz/static/js/dyviz/) ||
    (echo "Please run a linter and fix errors, e.g. pylint, flake8, pep8, etc."; false)
  # Make sure the docs build (including the examples).
  - cd docs && make html && cd ..
  # Make sure the library installs.
  - python setup.py install
  # Run benchmark
  - python bin/benchmark_pydy_code_gen.py 1 10
